azure:
    storage:
        account:
            name: Azure storage name
            key: Azure storage key
        container: Azure storage container name
    computerVision:
        key: cognitive services computer vision api key
    customVision:
        prediction:
            key: Custom vision service prediction key
            url: Custom vision service prediction url that using imageURL
response:
    imgUrl:
        adult: image URL when it was judged an adult
        racy: image URL when it was judged a racy

