azure:
    storage:
        account:
            name: your account name
            key: your account key
        container: your container name
    computerVision:
        key: your computer vision key
response:
    imgUrl:
        adult: image URL when it was judged an adult
        racy: image URL when it was judged a racy

