azure:
    storage:
        account:
            name: your account name
            key: your account key
        container: your container name
    computerVision:
        key: your computer vision key
cv:
    tempfile:
        dir: /static/img/
        before: sample.jpg
        after: temp_after.jpg

