azure:
    storage:
        account:
            name: your storage account name
            key: your storage key
        container: your container name
    computerVision:
        key: your computervision api key
cv:
    tempfile:
        dir: /static/img/
        before: sample.jpg
        after: temp_after.jpg

