azure:
    storage:
        account:
            name: maayasandbox
            key: 0MJqr4ADwBPBg/ilsnz7k+hlAIdaszl5dlrZiwtMMB2H3uqJxt4AE4BkM5gP/+wDnpujLHDRzHJUwo9KsNJd/g==
        container: azurestudy
cv:
    tempfile:
        dir: /static/img/
        before: sample.jpg
        after: temp_after.jpg

